"""remove STudent email test

Revision ID: 6164ac76530c
Revises: 9d9c0daf7f5a
Create Date: 2025-09-02 16:29:30.146593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6164ac76530c'
down_revision: Union[str, Sequence[str], None] = '9d9c0daf7f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
